"""Dokploy provider adapter.

This module is the single public compatibility surface for the Dokploy provider
adapter. Cohesive implementation lives in the sibling submodules:

- ``control_plane.dokploy.source``: config/source-of-truth/auth resolution and models.
- ``control_plane.dokploy.api``: generic Dokploy HTTP API, deployment, log, env, and
  schedule operations.
- ``control_plane.dokploy.compose``: compose rendering and source synchronization.
- ``control_plane.dokploy.post_deploy``: product-specific post-deploy and data-workflow
  orchestration and script rendering.

Repository callers import the canonical submodules directly; this surface is retained
for external consumers and the test suite.
"""

from control_plane.dokploy.source import (
    DEFAULT_DOKPLOY_DEPLOY_TIMEOUT_SECONDS as DEFAULT_DOKPLOY_DEPLOY_TIMEOUT_SECONDS,
    DEFAULT_DOKPLOY_HEALTH_TIMEOUT_SECONDS as DEFAULT_DOKPLOY_HEALTH_TIMEOUT_SECONDS,
    DEFAULT_DOKPLOY_HEALTHCHECK_PATH as DEFAULT_DOKPLOY_HEALTHCHECK_PATH,
    DEFAULT_CONTROL_PLANE_DOKPLOY_SOURCE_FILE as DEFAULT_CONTROL_PLANE_DOKPLOY_SOURCE_FILE,
    DEFAULT_CONTROL_PLANE_DOKPLOY_TARGET_IDS_FILE as DEFAULT_CONTROL_PLANE_DOKPLOY_TARGET_IDS_FILE,
    DEFAULT_STABLE_REMOTE_INSTANCES as DEFAULT_STABLE_REMOTE_INSTANCES,
    DokployTargetRecordStore as DokployTargetRecordStore,
    DokployTargetDefinition as DokployTargetDefinition,
    DokploySourceOfTruth as DokploySourceOfTruth,
    find_dokploy_target_definition as find_dokploy_target_definition,
    protected_shopify_store_keys_for_target_definition as protected_shopify_store_keys_for_target_definition,
    resolve_ship_timeout_seconds as resolve_ship_timeout_seconds,
    resolve_ship_health_timeout_seconds as resolve_ship_health_timeout_seconds,
    resolve_dokploy_ship_mode as resolve_dokploy_ship_mode,
    normalize_healthcheck_path as normalize_healthcheck_path,
    resolve_healthcheck_base_urls as resolve_healthcheck_base_urls,
    resolve_ship_healthcheck_urls as resolve_ship_healthcheck_urls,
    read_control_plane_environment_values as read_control_plane_environment_values,
    read_control_plane_dokploy_source_of_truth as read_control_plane_dokploy_source_of_truth,
    build_dokploy_target_record_from_definition as build_dokploy_target_record_from_definition,
    build_dokploy_source_of_truth_from_records as build_dokploy_source_of_truth_from_records,
    load_optional_dokploy_source_of_truth_from_store as load_optional_dokploy_source_of_truth_from_store,
    _load_optional_dokploy_source_of_truth_from_database as _load_optional_dokploy_source_of_truth_from_database,
    read_dokploy_config as read_dokploy_config,
    _normalize_dokploy_source_payload as _normalize_dokploy_source_payload,
    _resolve_dokploy_profile as _resolve_dokploy_profile,
    _resolve_dokploy_project_reference as _resolve_dokploy_project_reference,
    _expect_mapping as _expect_mapping,
    _merge_dokploy_settings as _merge_dokploy_settings,
)
from control_plane.dokploy.api import (
    DEFAULT_DOKPLOY_LOG_LINE_COUNT as DEFAULT_DOKPLOY_LOG_LINE_COUNT,
    MAX_DOKPLOY_LOG_LINE_COUNT as MAX_DOKPLOY_LOG_LINE_COUNT,
    _LIKELY_SECRET_LOG_VALUE_PATTERN as _LIKELY_SECRET_LOG_VALUE_PATTERN,
    _DOUBLE_QUOTED_SECRET_LOG_VALUE_PATTERN as _DOUBLE_QUOTED_SECRET_LOG_VALUE_PATTERN,
    _SINGLE_QUOTED_SECRET_LOG_VALUE_PATTERN as _SINGLE_QUOTED_SECRET_LOG_VALUE_PATTERN,
    _BEARER_LOG_VALUE_PATTERN as _BEARER_LOG_VALUE_PATTERN,
    _DATABASE_URI_CREDENTIAL_PATTERN as _DATABASE_URI_CREDENTIAL_PATTERN,
    _DOKPLOY_LOG_SINCE_PATTERN as _DOKPLOY_LOG_SINCE_PATTERN,
    _DOKPLOY_LOG_SEARCH_PATTERN as _DOKPLOY_LOG_SEARCH_PATTERN,
    JsonPrimitive as JsonPrimitive,
    JsonValue as JsonValue,
    JsonObject as JsonObject,
    trigger_deployment as trigger_deployment,
    latest_deployment_for_target as latest_deployment_for_target,
    list_deployments_for_target as list_deployments_for_target,
    deployment_for_target_by_title as deployment_for_target_by_title,
    fetch_dokploy_target_payload as fetch_dokploy_target_payload,
    normalize_dokploy_log_line_count as normalize_dokploy_log_line_count,
    normalize_dokploy_log_since as normalize_dokploy_log_since,
    normalize_dokploy_log_search as normalize_dokploy_log_search,
    redact_dokploy_log_line as redact_dokploy_log_line,
    normalize_dokploy_log_payload as normalize_dokploy_log_payload,
    fetch_dokploy_application_logs as fetch_dokploy_application_logs,
    fetch_dokploy_compose_logs as fetch_dokploy_compose_logs,
    fetch_dokploy_deployment_logs as fetch_dokploy_deployment_logs,
    _select_compose_log_container as _select_compose_log_container,
    _compose_log_container_is_web as _compose_log_container_is_web,
    _compose_log_container_has_web_service as _compose_log_container_has_web_service,
    _compose_log_container_has_web_name as _compose_log_container_has_web_name,
    _compose_log_container_service_names as _compose_log_container_service_names,
    _compose_log_container_names as _compose_log_container_names,
    _compose_log_container_name_is_web as _compose_log_container_name_is_web,
    parse_dokploy_env_text as parse_dokploy_env_text,
    render_dokploy_env_text_with_overrides as render_dokploy_env_text_with_overrides,
    serialize_dokploy_env_text as serialize_dokploy_env_text,
    update_dokploy_target_env as update_dokploy_target_env,
    wait_for_target_deployment as wait_for_target_deployment,
    resolve_dokploy_user_id as resolve_dokploy_user_id,
    latest_deployment_for_schedule as latest_deployment_for_schedule,
    wait_for_dokploy_schedule_deployment as wait_for_dokploy_schedule_deployment,
    list_dokploy_schedules as list_dokploy_schedules,
    find_matching_dokploy_schedule as find_matching_dokploy_schedule,
    schedule_key as schedule_key,
    upsert_dokploy_schedule as upsert_dokploy_schedule,
    deployment_key as deployment_key,
    deployment_key_from_wait_result as deployment_key_from_wait_result,
    deployment_status as deployment_status,
    dokploy_request as dokploy_request,
    _string_items as _string_items,
    _normalize_json_value as _normalize_json_value,
    as_json_object as as_json_object,
    extract_schedules as extract_schedules,
    extract_deployments as extract_deployments,
    _collect_object_items as _collect_object_items,
    _wait_for_deployment_status as _wait_for_deployment_status,
    _latest_deployment_from_list as _latest_deployment_from_list,
    _deployment_sort_key as _deployment_sort_key,
    _deployment_status as _deployment_status,
)
from control_plane.dokploy.compose import (
    ODOO_RAW_COMPOSE_REQUIRED_SERVICES as ODOO_RAW_COMPOSE_REQUIRED_SERVICES,
    _traefik_route_name as _traefik_route_name,
    _render_odoo_web_traefik_labels as _render_odoo_web_traefik_labels,
    render_odoo_raw_compose_file as render_odoo_raw_compose_file,
    compose_file_sha256 as compose_file_sha256,
    _compose_file_has_required_service as _compose_file_has_required_service,
    validate_odoo_raw_compose_file as validate_odoo_raw_compose_file,
    update_dokploy_target_source as update_dokploy_target_source,
    sync_dokploy_compose_raw_source as sync_dokploy_compose_raw_source,
    ensure_compose_web_domain_route as ensure_compose_web_domain_route,
    fetch_dokploy_converted_compose_file as fetch_dokploy_converted_compose_file,
    _build_raw_compose_evidence as _build_raw_compose_evidence,
)
from control_plane.dokploy.post_deploy import (
    DOKPLOY_DATA_WORKFLOW_SCHEDULE_NAME as DOKPLOY_DATA_WORKFLOW_SCHEDULE_NAME,
    DOKPLOY_ODOO_BOOTSTRAP_SCHEDULE_NAME as DOKPLOY_ODOO_BOOTSTRAP_SCHEDULE_NAME,
    DOKPLOY_ODOO_BACKUP_GATE_SCHEDULE_NAME as DOKPLOY_ODOO_BACKUP_GATE_SCHEDULE_NAME,
    DOKPLOY_ODOO_BACKUP_VERIFICATION_SCHEDULE_NAME as DOKPLOY_ODOO_BACKUP_VERIFICATION_SCHEDULE_NAME,
    DOKPLOY_MANUAL_ONLY_CRON_EXPRESSION as DOKPLOY_MANUAL_ONLY_CRON_EXPRESSION,
    DOKPLOY_RUNNING_DEPLOYMENT_STATUSES as DOKPLOY_RUNNING_DEPLOYMENT_STATUSES,
    DOKPLOY_CANCELLED_DEPLOYMENT_STATUSES as DOKPLOY_CANCELLED_DEPLOYMENT_STATUSES,
    DOKPLOY_SUCCESS_DEPLOYMENT_STATUSES as DOKPLOY_SUCCESS_DEPLOYMENT_STATUSES,
    POST_DEPLOY_UPDATE_IGNORED_ENV_KEYS as POST_DEPLOY_UPDATE_IGNORED_ENV_KEYS,
    POST_DEPLOY_UPDATE_ALLOWED_ENV_KEYS as POST_DEPLOY_UPDATE_ALLOWED_ENV_KEYS,
    ODOO_INSTANCE_OVERRIDES_PAYLOAD_ENV_KEY as ODOO_INSTANCE_OVERRIDES_PAYLOAD_ENV_KEY,
    LAUNCHPLANE_INSTANCE_OVERRIDES_REQUIRED_ENV_KEY as LAUNCHPLANE_INSTANCE_OVERRIDES_REQUIRED_ENV_KEY,
    LAUNCHPLANE_WEBSITE_BOOTSTRAP_REQUIRED_ENV_KEY as LAUNCHPLANE_WEBSITE_BOOTSTRAP_REQUIRED_ENV_KEY,
    ODOO_RUNTIME_OVERRIDE_TARGET_ENV_KEYS as ODOO_RUNTIME_OVERRIDE_TARGET_ENV_KEYS,
    ODOO_UPSTREAM_RESTORE_WORKFLOW_ENV_KEYS as ODOO_UPSTREAM_RESTORE_WORKFLOW_ENV_KEYS,
    DEFAULT_DATA_WORKFLOW_LOCK_PATH as DEFAULT_DATA_WORKFLOW_LOCK_PATH,
    DEFAULT_ODOO_BACKUP_ROOT as DEFAULT_ODOO_BACKUP_ROOT,
    ODOO_POST_DEPLOY_BOOLEAN_READBACK_MARKERS as ODOO_POST_DEPLOY_BOOLEAN_READBACK_MARKERS,
    ODOO_POST_DEPLOY_NUMERIC_READBACK_MARKERS as ODOO_POST_DEPLOY_NUMERIC_READBACK_MARKERS,
    ODOO_POST_DEPLOY_READBACK_MARKERS as ODOO_POST_DEPLOY_READBACK_MARKERS,
    ODOO_BACKUP_VERIFICATION_RESULT_MARKER as ODOO_BACKUP_VERIFICATION_RESULT_MARKER,
    ODOO_BACKUP_VERIFICATION_RESULT_FIELDS as ODOO_BACKUP_VERIFICATION_RESULT_FIELDS,
    run_compose_post_deploy_update as run_compose_post_deploy_update,
    run_compose_odoo_stable_bootstrap as run_compose_odoo_stable_bootstrap,
    run_compose_odoo_backup_gate as run_compose_odoo_backup_gate,
    run_compose_odoo_backup_verification as run_compose_odoo_backup_verification,
    extract_odoo_backup_verification_result as extract_odoo_backup_verification_result,
    extract_odoo_post_deploy_readback_markers as extract_odoo_post_deploy_readback_markers,
    _read_odoo_post_deploy_log_markers as _read_odoo_post_deploy_log_markers,
    _build_dokploy_data_workflow_schedule_app_name as _build_dokploy_data_workflow_schedule_app_name,
    _resolve_dokploy_schedule_runtime as _resolve_dokploy_schedule_runtime,
    _build_dokploy_data_workflow_script as _build_dokploy_data_workflow_script,
    _build_dokploy_odoo_backup_gate_script as _build_dokploy_odoo_backup_gate_script,
    _build_dokploy_odoo_backup_verification_script as _build_dokploy_odoo_backup_verification_script,
    _render_docker_exec_environment_lines as _render_docker_exec_environment_lines,
    _render_required_environment_key_lines as _render_required_environment_key_lines,
    _render_bash_array_assignment_lines as _render_bash_array_assignment_lines,
    _schedule_deployments as _schedule_deployments,
    _has_running_schedule_deployment as _has_running_schedule_deployment,
    _should_clear_stale_data_workflow_lock as _should_clear_stale_data_workflow_lock,
    _apply_post_deploy_env_file_overrides as _apply_post_deploy_env_file_overrides,
    _resolve_upstream_restore_workflow_environment as _resolve_upstream_restore_workflow_environment,
)

deployment_log_id = deployment_key

__all__ = [
    "DEFAULT_DOKPLOY_DEPLOY_TIMEOUT_SECONDS",
    "DEFAULT_DOKPLOY_HEALTH_TIMEOUT_SECONDS",
    "DEFAULT_DOKPLOY_HEALTHCHECK_PATH",
    "DEFAULT_CONTROL_PLANE_DOKPLOY_SOURCE_FILE",
    "DEFAULT_CONTROL_PLANE_DOKPLOY_TARGET_IDS_FILE",
    "DEFAULT_STABLE_REMOTE_INSTANCES",
    "DokployTargetRecordStore",
    "DokployTargetDefinition",
    "DokploySourceOfTruth",
    "find_dokploy_target_definition",
    "protected_shopify_store_keys_for_target_definition",
    "resolve_ship_timeout_seconds",
    "resolve_ship_health_timeout_seconds",
    "resolve_dokploy_ship_mode",
    "normalize_healthcheck_path",
    "resolve_healthcheck_base_urls",
    "resolve_ship_healthcheck_urls",
    "read_control_plane_environment_values",
    "read_control_plane_dokploy_source_of_truth",
    "build_dokploy_target_record_from_definition",
    "build_dokploy_source_of_truth_from_records",
    "load_optional_dokploy_source_of_truth_from_store",
    "_load_optional_dokploy_source_of_truth_from_database",
    "read_dokploy_config",
    "_normalize_dokploy_source_payload",
    "_resolve_dokploy_profile",
    "_resolve_dokploy_project_reference",
    "_expect_mapping",
    "_merge_dokploy_settings",
    "DEFAULT_DOKPLOY_LOG_LINE_COUNT",
    "MAX_DOKPLOY_LOG_LINE_COUNT",
    "_LIKELY_SECRET_LOG_VALUE_PATTERN",
    "_DOUBLE_QUOTED_SECRET_LOG_VALUE_PATTERN",
    "_SINGLE_QUOTED_SECRET_LOG_VALUE_PATTERN",
    "_BEARER_LOG_VALUE_PATTERN",
    "_DATABASE_URI_CREDENTIAL_PATTERN",
    "_DOKPLOY_LOG_SINCE_PATTERN",
    "_DOKPLOY_LOG_SEARCH_PATTERN",
    "JsonPrimitive",
    "JsonValue",
    "JsonObject",
    "trigger_deployment",
    "latest_deployment_for_target",
    "list_deployments_for_target",
    "deployment_for_target_by_title",
    "fetch_dokploy_target_payload",
    "normalize_dokploy_log_line_count",
    "normalize_dokploy_log_since",
    "normalize_dokploy_log_search",
    "redact_dokploy_log_line",
    "normalize_dokploy_log_payload",
    "fetch_dokploy_application_logs",
    "fetch_dokploy_compose_logs",
    "fetch_dokploy_deployment_logs",
    "_select_compose_log_container",
    "_compose_log_container_is_web",
    "_compose_log_container_has_web_service",
    "_compose_log_container_has_web_name",
    "_compose_log_container_service_names",
    "_compose_log_container_names",
    "_compose_log_container_name_is_web",
    "parse_dokploy_env_text",
    "render_dokploy_env_text_with_overrides",
    "serialize_dokploy_env_text",
    "update_dokploy_target_env",
    "wait_for_target_deployment",
    "resolve_dokploy_user_id",
    "latest_deployment_for_schedule",
    "wait_for_dokploy_schedule_deployment",
    "list_dokploy_schedules",
    "find_matching_dokploy_schedule",
    "schedule_key",
    "upsert_dokploy_schedule",
    "deployment_key",
    "deployment_log_id",
    "deployment_key_from_wait_result",
    "deployment_status",
    "dokploy_request",
    "_string_items",
    "_normalize_json_value",
    "as_json_object",
    "extract_schedules",
    "extract_deployments",
    "_collect_object_items",
    "_wait_for_deployment_status",
    "_latest_deployment_from_list",
    "_deployment_sort_key",
    "_deployment_status",
    "ODOO_RAW_COMPOSE_REQUIRED_SERVICES",
    "_traefik_route_name",
    "_render_odoo_web_traefik_labels",
    "render_odoo_raw_compose_file",
    "compose_file_sha256",
    "_compose_file_has_required_service",
    "validate_odoo_raw_compose_file",
    "update_dokploy_target_source",
    "sync_dokploy_compose_raw_source",
    "ensure_compose_web_domain_route",
    "fetch_dokploy_converted_compose_file",
    "_build_raw_compose_evidence",
    "DOKPLOY_DATA_WORKFLOW_SCHEDULE_NAME",
    "DOKPLOY_ODOO_BOOTSTRAP_SCHEDULE_NAME",
    "DOKPLOY_ODOO_BACKUP_GATE_SCHEDULE_NAME",
    "DOKPLOY_ODOO_BACKUP_VERIFICATION_SCHEDULE_NAME",
    "DOKPLOY_MANUAL_ONLY_CRON_EXPRESSION",
    "DOKPLOY_RUNNING_DEPLOYMENT_STATUSES",
    "DOKPLOY_CANCELLED_DEPLOYMENT_STATUSES",
    "DOKPLOY_SUCCESS_DEPLOYMENT_STATUSES",
    "POST_DEPLOY_UPDATE_IGNORED_ENV_KEYS",
    "POST_DEPLOY_UPDATE_ALLOWED_ENV_KEYS",
    "ODOO_INSTANCE_OVERRIDES_PAYLOAD_ENV_KEY",
    "LAUNCHPLANE_INSTANCE_OVERRIDES_REQUIRED_ENV_KEY",
    "LAUNCHPLANE_WEBSITE_BOOTSTRAP_REQUIRED_ENV_KEY",
    "ODOO_RUNTIME_OVERRIDE_TARGET_ENV_KEYS",
    "ODOO_UPSTREAM_RESTORE_WORKFLOW_ENV_KEYS",
    "DEFAULT_DATA_WORKFLOW_LOCK_PATH",
    "DEFAULT_ODOO_BACKUP_ROOT",
    "ODOO_POST_DEPLOY_BOOLEAN_READBACK_MARKERS",
    "ODOO_POST_DEPLOY_NUMERIC_READBACK_MARKERS",
    "ODOO_POST_DEPLOY_READBACK_MARKERS",
    "ODOO_BACKUP_VERIFICATION_RESULT_MARKER",
    "ODOO_BACKUP_VERIFICATION_RESULT_FIELDS",
    "run_compose_post_deploy_update",
    "run_compose_odoo_stable_bootstrap",
    "run_compose_odoo_backup_gate",
    "run_compose_odoo_backup_verification",
    "extract_odoo_backup_verification_result",
    "extract_odoo_post_deploy_readback_markers",
    "_read_odoo_post_deploy_log_markers",
    "_build_dokploy_data_workflow_schedule_app_name",
    "_resolve_dokploy_schedule_runtime",
    "_build_dokploy_data_workflow_script",
    "_build_dokploy_odoo_backup_gate_script",
    "_build_dokploy_odoo_backup_verification_script",
    "_render_docker_exec_environment_lines",
    "_render_required_environment_key_lines",
    "_render_bash_array_assignment_lines",
    "_schedule_deployments",
    "_has_running_schedule_deployment",
    "_should_clear_stale_data_workflow_lock",
    "_apply_post_deploy_env_file_overrides",
    "_resolve_upstream_restore_workflow_environment",
]
