"""Bounded generator attribution; this never verifies generated byte freshness.

Only the winning path rule expands its generators. Ancestors contribute their
own floors, never their products or generator edges. Frozen leaf contributions
preserve the authority behind an aggregate for the scoped decision digest.
"""

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from types import MappingProxyType

from control_plane.contracts.change_impact import (
    ChangeImpactComponentRule,
    ChangeImpactPolicyRecord,
    ChangeImpactProductScope,
)


class ProductAuthorityMode(StrEnum):
    DIRECT = "direct"
    DECLARED_NONE = "declared_none"
    GENERATED = "generated"
    LEGACY_EMPTY = "legacy_empty"


def product_authority_mode(rule: ChangeImpactComponentRule) -> ProductAuthorityMode:
    if rule.generated_by is not None:
        return ProductAuthorityMode.GENERATED
    if rule.affected_products:
        return ProductAuthorityMode.DIRECT
    if rule.product_impact == "declared_none":
        return ProductAuthorityMode.DECLARED_NONE
    return ProductAuthorityMode.LEGACY_EMPTY


@dataclass(frozen=True, slots=True)
class ChangeImpactFloors:
    sensitive: bool = False
    governance: bool = False
    production: bool = False


def rule_floors(rule: ChangeImpactComponentRule) -> ChangeImpactFloors:
    return ChangeImpactFloors(
        sensitive=rule.review_tier == "sensitive" or bool(rule.governance_impact),
        governance=bool(rule.governance_impact),
        production=bool(rule.production_affecting),
    )


def join_floors(*floors: ChangeImpactFloors) -> ChangeImpactFloors:
    return ChangeImpactFloors(
        sensitive=any(floor.sensitive for floor in floors),
        governance=any(floor.governance for floor in floors),
        production=any(floor.production for floor in floors),
    )


@dataclass(frozen=True, slots=True)
class GeneratorAncestorFloor:
    component: str
    prefix: str
    floors: ChangeImpactFloors


@dataclass(frozen=True, slots=True)
class GeneratorContribution:
    component: str
    affected_products: tuple[ChangeImpactProductScope, ...]
    declared_none: bool
    own_floors: ChangeImpactFloors
    ancestor_floors: tuple[GeneratorAncestorFloor, ...]


@dataclass(frozen=True, slots=True)
class GeneratedBoundary:
    component: str
    generators: tuple[GeneratorContribution, ...]
    affected_products: tuple[ChangeImpactProductScope, ...]
    declared_none: bool
    floors: ChangeImpactFloors


def validate_generated_boundaries(policy: ChangeImpactPolicyRecord) -> None:
    """Reject nonterminal graphs before any v2 policy can be used."""
    rules = {rule.component: rule for rule in policy.component_rules}
    edge_count = 0
    for rule in policy.component_rules:
        if rule.generated_by is None:
            continue
        edge_count += len(rule.generated_by)
        if edge_count > 400:
            raise ValueError("generated boundary policy exceeds 400 edges")
        for component in rule.generated_by:
            if component == rule.component:
                raise ValueError("generated boundary cannot reference itself")
            leaf = rules.get(component)
            if leaf is None:
                raise ValueError("generated boundary references missing component")
            mode = product_authority_mode(leaf)
            if mode == ProductAuthorityMode.GENERATED:
                raise ValueError("generated boundary requires terminal components")
            if mode == ProductAuthorityMode.LEGACY_EMPTY:
                raise ValueError("generated boundary cannot use implicit empty authority")


def resolve_generated_boundaries(
    policy: ChangeImpactPolicyRecord,
) -> Mapping[str, GeneratedBoundary]:
    """Resolve validated depth-1 mappings once, independently of changed paths."""
    if policy.classification_model != "v2":
        return MappingProxyType({})
    validate_generated_boundaries(policy)
    rules = {rule.component: rule for rule in policy.component_rules}
    resolved: dict[str, GeneratedBoundary] = {}
    for rule in policy.component_rules:
        if rule.generated_by is None:
            continue
        contributions: list[GeneratorContribution] = []
        floors: list[ChangeImpactFloors] = []
        products: set[ChangeImpactProductScope] = set()
        for component in rule.generated_by:
            leaf = rules[component]
            ancestors = tuple(
                sorted(
                    {
                        GeneratorAncestorFloor(ancestor.component, prefix, rule_floors(ancestor))
                        for ancestor in policy.component_rules
                        if ancestor.component != component
                        for prefix in ancestor.path_prefixes
                        if any(path.startswith(f"{prefix}/") for path in leaf.path_prefixes)
                    },
                    key=lambda ancestor: (ancestor.component, ancestor.prefix),
                )
            )
            own_floors = rule_floors(leaf)
            floors.extend((own_floors, *(ancestor.floors for ancestor in ancestors)))
            products.update(leaf.affected_products)
            contributions.append(
                GeneratorContribution(
                    component=component,
                    affected_products=leaf.affected_products,
                    declared_none=leaf.product_impact == "declared_none",
                    own_floors=own_floors,
                    ancestor_floors=ancestors,
                )
            )
        resolved[rule.component] = GeneratedBoundary(
            component=rule.component,
            generators=tuple(contributions),
            affected_products=tuple(
                sorted(
                    products,
                    key=lambda scope: (
                        scope.product,
                        scope.system,
                        scope.owner_action,
                        scope.owner_environment,
                    ),
                )
            ),
            declared_none=all(leaf.declared_none for leaf in contributions),
            floors=join_floors(*floors),
        )
    return MappingProxyType(resolved)
