"""baseline current schema

Revision ID: fe94a0486977
Revises:
Create Date: 2026-04-28 15:18:59.547980+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "fe94a0486977"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launchplane_artifact_manifests",
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("source_commit", sa.String(), nullable=False),
        sa.Column("image_repository", sa.String(), nullable=False),
        sa.Column("image_digest", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index(
        "launchplane_artifact_manifests_artifact_idx",
        "launchplane_artifact_manifests",
        [sa.text("artifact_id DESC")],
    )
    op.create_table(
        "launchplane_backup_gates",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        "launchplane_backup_gates_context_instance_idx",
        "launchplane_backup_gates",
        ["context", "instance", sa.text("created_at DESC")],
    )
    op.create_table(
        "launchplane_deployments",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("source_git_ref", sa.String(), nullable=False),
        sa.Column("deploy_started_at", sa.String(), nullable=False),
        sa.Column("deploy_finished_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        "launchplane_deployments_context_instance_idx",
        "launchplane_deployments",
        [
            "context",
            "instance",
            sa.text("deploy_finished_at DESC"),
            sa.text("deploy_started_at DESC"),
        ],
    )
    op.create_table(
        "launchplane_dokploy_target_ids",
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("context", "instance"),
    )
    op.create_index(
        "launchplane_dokploy_target_ids_updated_idx",
        "launchplane_dokploy_target_ids",
        [sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_dokploy_targets",
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("context", "instance"),
    )
    op.create_index(
        "launchplane_dokploy_targets_updated_idx",
        "launchplane_dokploy_targets",
        [sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_idempotency_records",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("route_path", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("request_fingerprint", sa.String(), nullable=False),
        sa.Column("response_status_code", sa.Integer(), nullable=False),
        sa.Column("response_trace_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        "launchplane_idempotency_scope_route_key_idx",
        "launchplane_idempotency_records",
        ["scope", "route_path", "idempotency_key"],
        unique=True,
    )
    op.create_table(
        "launchplane_inventory",
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("source_git_ref", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deployment_record_id", sa.String(), nullable=False),
        sa.Column("promotion_record_id", sa.String(), nullable=False),
        sa.Column("promoted_from_instance", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("context", "instance"),
    )
    op.create_index(
        "launchplane_inventory_updated_idx", "launchplane_inventory", [sa.text("updated_at DESC")]
    )
    op.create_table(
        "launchplane_odoo_instance_overrides",
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("context", "instance"),
    )
    op.create_index(
        "launchplane_odoo_instance_overrides_updated_idx",
        "launchplane_odoo_instance_overrides",
        [sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_preview_generations",
        sa.Column("generation_id", sa.String(), nullable=False),
        sa.Column("preview_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("requested_at", sa.String(), nullable=False),
        sa.Column("finished_at", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("generation_id"),
    )
    op.create_index(
        "launchplane_preview_generations_preview_idx",
        "launchplane_preview_generations",
        ["preview_id", sa.text("sequence DESC"), sa.text("requested_at DESC")],
    )
    op.create_table(
        "launchplane_preview_records",
        sa.Column("preview_id", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("anchor_repo", sa.String(), nullable=False),
        sa.Column("anchor_pr_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("preview_id"),
    )
    op.create_index(
        "launchplane_preview_records_lookup_idx",
        "launchplane_preview_records",
        ["context", "anchor_repo", "anchor_pr_number", sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_promotions",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("from_instance", sa.String(), nullable=False),
        sa.Column("to_instance", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("deploy_started_at", sa.String(), nullable=False),
        sa.Column("deploy_finished_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        "launchplane_promotions_context_path_idx",
        "launchplane_promotions",
        [
            "context",
            "from_instance",
            "to_instance",
            sa.text("deploy_finished_at DESC"),
            sa.text("deploy_started_at DESC"),
        ],
    )
    op.create_table(
        "launchplane_release_tuples",
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("tuple_id", sa.String(), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("minted_at", sa.String(), nullable=False),
        sa.Column("provenance", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("context", "channel"),
    )
    op.create_index(
        "launchplane_release_tuples_minted_idx",
        "launchplane_release_tuples",
        [sa.text("minted_at DESC")],
    )
    op.create_table(
        "launchplane_runtime_environments",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("scope", "context", "instance"),
    )
    op.create_index(
        "launchplane_runtime_environments_updated_idx",
        "launchplane_runtime_environments",
        [sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_secret_audit_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("secret_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "launchplane_secret_audit_events_secret_idx",
        "launchplane_secret_audit_events",
        ["secret_id", sa.text("recorded_at DESC")],
    )
    op.create_table(
        "launchplane_secret_bindings",
        sa.Column("binding_id", sa.String(), nullable=False),
        sa.Column("secret_id", sa.String(), nullable=False),
        sa.Column("integration", sa.String(), nullable=False),
        sa.Column("binding_key", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("binding_id"),
    )
    op.create_index(
        "launchplane_secret_bindings_lookup_idx",
        "launchplane_secret_bindings",
        ["integration", "context", "instance", "binding_key", sa.text("updated_at DESC")],
    )
    op.create_table(
        "launchplane_secret_versions",
        sa.Column("version_id", sa.String(), nullable=False),
        sa.Column("secret_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        "launchplane_secret_versions_secret_idx",
        "launchplane_secret_versions",
        ["secret_id", sa.text("created_at DESC")],
    )
    op.create_table(
        "launchplane_secrets",
        sa.Column("secret_id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("integration", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_version_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("secret_id"),
    )
    op.create_index(
        "launchplane_secrets_lookup_idx",
        "launchplane_secrets",
        ["integration", "context", "instance", sa.text("updated_at DESC")],
    )
    op.create_index(
        "launchplane_secrets_scope_name_idx",
        "launchplane_secrets",
        ["scope", "integration", "name", "context", "instance"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("launchplane_secrets_scope_name_idx", table_name="launchplane_secrets")
    op.drop_index("launchplane_secrets_lookup_idx", table_name="launchplane_secrets")
    op.drop_table("launchplane_secrets")
    op.drop_index(
        "launchplane_secret_versions_secret_idx", table_name="launchplane_secret_versions"
    )
    op.drop_table("launchplane_secret_versions")
    op.drop_index(
        "launchplane_secret_bindings_lookup_idx", table_name="launchplane_secret_bindings"
    )
    op.drop_table("launchplane_secret_bindings")
    op.drop_index(
        "launchplane_secret_audit_events_secret_idx", table_name="launchplane_secret_audit_events"
    )
    op.drop_table("launchplane_secret_audit_events")
    op.drop_index(
        "launchplane_runtime_environments_updated_idx",
        table_name="launchplane_runtime_environments",
    )
    op.drop_table("launchplane_runtime_environments")
    op.drop_index("launchplane_release_tuples_minted_idx", table_name="launchplane_release_tuples")
    op.drop_table("launchplane_release_tuples")
    op.drop_index("launchplane_promotions_context_path_idx", table_name="launchplane_promotions")
    op.drop_table("launchplane_promotions")
    op.drop_index(
        "launchplane_preview_records_lookup_idx", table_name="launchplane_preview_records"
    )
    op.drop_table("launchplane_preview_records")
    op.drop_index(
        "launchplane_preview_generations_preview_idx", table_name="launchplane_preview_generations"
    )
    op.drop_table("launchplane_preview_generations")
    op.drop_index(
        "launchplane_odoo_instance_overrides_updated_idx",
        table_name="launchplane_odoo_instance_overrides",
    )
    op.drop_table("launchplane_odoo_instance_overrides")
    op.drop_index("launchplane_inventory_updated_idx", table_name="launchplane_inventory")
    op.drop_table("launchplane_inventory")
    op.drop_index(
        "launchplane_idempotency_scope_route_key_idx", table_name="launchplane_idempotency_records"
    )
    op.drop_table("launchplane_idempotency_records")
    op.drop_index(
        "launchplane_dokploy_targets_updated_idx", table_name="launchplane_dokploy_targets"
    )
    op.drop_table("launchplane_dokploy_targets")
    op.drop_index(
        "launchplane_dokploy_target_ids_updated_idx", table_name="launchplane_dokploy_target_ids"
    )
    op.drop_table("launchplane_dokploy_target_ids")
    op.drop_index(
        "launchplane_deployments_context_instance_idx", table_name="launchplane_deployments"
    )
    op.drop_table("launchplane_deployments")
    op.drop_index(
        "launchplane_backup_gates_context_instance_idx", table_name="launchplane_backup_gates"
    )
    op.drop_table("launchplane_backup_gates")
    op.drop_index(
        "launchplane_artifact_manifests_artifact_idx", table_name="launchplane_artifact_manifests"
    )
    op.drop_table("launchplane_artifact_manifests")
    # ### end Alembic commands ###
